#=========================================================================
# TravisCI Setup
#=========================================================================

#------------------------------------------------------------------------
# language and build matrix
#------------------------------------------------------------------------

language: python
python:
 - "3.7"

#------------------------------------------------------------------------
# install dependencies
#------------------------------------------------------------------------

install:
 - pip install --upgrade pip
 - pip install --upgrade hypothesis
 - pip install pymtl3
 - pip list

#------------------------------------------------------------------------
# test runner
#------------------------------------------------------------------------

script:
 - py.test

